services:
  substrate-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args: {}
    image: substrate-dev:latest
    platform: linux/amd64
    privileged: true
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    cap_add:
      - ALL
    working_dir: /src
    volumes:
      - .:/src
    environment:
      - HOME=/root
      - RUST_LOG=info
      - CODEX_UNSAFE_ALLOW_NO_SANDBOX=1
    entrypoint: ["/usr/local/bin/dev-entrypoint.sh"]
    command: ["bash"]
