#![cfg(unix)]

#[path = "common.rs"]
mod common;

use common::{binary_path, ensure_substrate_built, shared_tmpdir};
use serde_json::{json, Value};
use std::fs::{self, OpenOptions};
use std::io::Write;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::Command;
use tempfile::{Builder, TempDir};
use transport_api_types::{InstallBootstrapContextCarrierV1, InstallBootstrapContextV1};

struct DoctorFixture {
    _temp: TempDir,
    home: PathBuf,
    trace: PathBuf,
    shim_dir: PathBuf,
    health_dir: PathBuf,
    passwd_preload: PathBuf,
}

impl DoctorFixture {
    fn new(manifest_contents: &str) -> Self {
        let safe_parent = std::env::var_os("XDG_RUNTIME_DIR")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from(format!("/run/user/{}", unsafe { libc::geteuid() })));
        let temp = Builder::new()
            .prefix("substrate-doctor-r2-")
            .tempdir_in(safe_parent)
            .expect("allocate secure shim doctor fixture root");
        let home = temp.path().join("home");
        let prefix = home.join(".substrate");
        let shim_dir = prefix.join("shims");
        fs::create_dir_all(&shim_dir).expect("prepare shim directory");
        fs::set_permissions(&home, fs::Permissions::from_mode(0o700))
            .expect("secure fixture account home");
        fs::set_permissions(&prefix, fs::Permissions::from_mode(0o700))
            .expect("secure selected prefix");
        let trace = prefix.join("trace.jsonl");
        fs::write(&trace, "").expect("create trace fixture");
        fs::write(
            prefix.join("manager_init.sh"),
            "# Generated by shim doctor tests\n",
        )
        .expect("seed manager init fixture");
        fs::write(prefix.join("manager_hooks.yaml"), manifest_contents)
            .expect("project manager manifest into selected prefix");
        let health_dir = prefix.join("health");
        fs::create_dir_all(&health_dir).expect("create health fixture directory");
        let passwd_preload = compile_passwd_preload(temp.path());
        let fixture = Self {
            _temp: temp,
            home,
            trace,
            shim_dir,
            health_dir,
            passwd_preload,
        };
        fixture.write_default_world_fixtures();
        fixture
    }

    fn command(&self) -> Command {
        ensure_substrate_built();
        let uid = unsafe { libc::geteuid() };
        let gid = unsafe { libc::getegid() };
        let prefix = self.home.join(".substrate");
        let mut command = Command::new(binary_path());
        command
            .env("TMPDIR", shared_tmpdir())
            .env("HOME", &self.home)
            .env("USERPROFILE", &self.home)
            .env("SUBSTRATE_HOME", &prefix)
            .env("SUBSTRATE_ROOT", &prefix)
            .env("SHIM_TRACE_LOG", &self.trace)
            .env("SUBSTRATE_OVERRIDE_WORLD", "disabled")
            .env("LD_PRELOAD", &self.passwd_preload)
            .env("SUBSTRATE_R2_TEST_UID", uid.to_string())
            .env("SUBSTRATE_R2_TEST_GID", gid.to_string())
            .env("SUBSTRATE_R2_TEST_ACCOUNT", "substrate-r2-test")
            .env("SUBSTRATE_R2_TEST_ACCOUNT_HOME", &self.home)
            .env_remove("SHIM_ORIGINAL_PATH")
            .env_remove("SUBSTRATE_WORLD")
            .env_remove("SUBSTRATE_WORLD_ENABLED")
            .env_remove("SUBSTRATE_WORLD_ID")
            .current_dir(&self.home)
            .arg("--install-prefix")
            .arg(prefix);
        command
    }

    fn write_default_world_fixtures(&self) {
        self.write_world_doctor_fixture(json!({
            "schema_version": 1,
            "platform": std::env::consts::OS,
            "world_enabled": true,
            "ok": true,
            "host": {
                "platform": std::env::consts::OS,
                "ok": true,
                "world_fs_mode": "writable",
                "world_fs_isolation": "workspace",
                "world_fs_require_world": true
            },
            "world": {
                "status": "ok",
                "schema_version": 2,
                "ok": true,
                "collected_at_utc": "2026-01-08T00:00:00Z",
                "policy_snapshot_v1_supported": true,
                "policy_resolution_mode": null,
                "netfilter_status": {
                    "requested": false,
                    "enabled": false,
                    "world_netfilter_enable_present": false,
                    "last_failure_reason": null
                },
                "landlock": { "supported": true, "abi": 3, "reason": null },
                "world_fs_strategy": {
                    "primary": "overlay",
                    "fallback": "fuse",
                    "probe": {
                        "id": "enumeration_v1",
                        "probe_file": ".substrate_enum_probe",
                        "result": "pass",
                        "failure_reason": null
                    }
                }
            }
        }));
        self.write_world_deps_fixture(json!({
            "schema_version": 1,
            "cwd": self.home,
            "inventory_packages": 0,
            "inventory_bundles": 0,
            "inventory_mode": "merged",
            "builtins": "enabled",
            "enabled": [],
            "applied": []
        }));
    }

    fn write_world_doctor_fixture(&self, value: Value) {
        fs::write(self.health_dir.join("world_doctor.json"), value.to_string())
            .expect("write world doctor fixture");
    }

    fn write_world_deps_fixture(&self, value: Value) {
        fs::write(self.health_dir.join("world_deps.json"), value.to_string())
            .expect("write world deps fixture");
    }

    fn write_hint_event(&self, name: &str, hint: &str, ts: &str) {
        let event = json!({
            "ts": ts,
            "event_type": "command_complete",
            "component": "shim",
            "manager_hint": { "name": name, "hint": hint, "pattern": ".*", "ts": ts }
        });
        let mut file = OpenOptions::new()
            .append(true)
            .open(&self.trace)
            .expect("open trace fixture");
        writeln!(file, "{event}").expect("write hint fixture");
    }

    fn home(&self) -> &Path {
        &self.home
    }

    fn shim_dir(&self) -> &Path {
        &self.shim_dir
    }

    fn bashenv_path(&self) -> PathBuf {
        self.home.join(".substrate_bashenv")
    }
}

fn compile_passwd_preload(root: &Path) -> PathBuf {
    let source = root.join("passwd_preload.c");
    let library = root.join("passwd_preload.so");
    fs::write(
        &source,
        r#"#define _GNU_SOURCE
#include <dlfcn.h>
#include <errno.h>
#include <pwd.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>

typedef int (*real_getpwuid_r_fn)(uid_t, struct passwd *, char *, size_t, struct passwd **);

int getpwuid_r(uid_t uid, struct passwd *pwd, char *buf, size_t buflen, struct passwd **result) {
    const char *target_uid = getenv("SUBSTRATE_R2_TEST_UID");
    if (target_uid == NULL || uid != (uid_t)strtoul(target_uid, NULL, 10)) {
        static real_getpwuid_r_fn real_fn;
        if (real_fn == NULL) real_fn = (real_getpwuid_r_fn)dlsym(RTLD_NEXT, "getpwuid_r");
        return real_fn(uid, pwd, buf, buflen, result);
    }
    const char *name = getenv("SUBSTRATE_R2_TEST_ACCOUNT");
    const char *home = getenv("SUBSTRATE_R2_TEST_ACCOUNT_HOME");
    const char *target_gid = getenv("SUBSTRATE_R2_TEST_GID");
    const char *passwd = "x";
    const char *gecos = "Substrate R2 Test";
    const char *shell = "/bin/sh";
    size_t need = strlen(name) + strlen(home) + strlen(passwd) + strlen(gecos) + strlen(shell) + 5;
    if (buflen < need) { *result = NULL; return ERANGE; }
    char *cursor = buf;
#define COPY_FIELD(field, value) do { size_t n = strlen(value) + 1; memcpy(cursor, value, n); pwd->field = cursor; cursor += n; } while (0)
    COPY_FIELD(pw_name, name);
    COPY_FIELD(pw_passwd, passwd);
    COPY_FIELD(pw_gecos, gecos);
    COPY_FIELD(pw_dir, home);
    COPY_FIELD(pw_shell, shell);
    pwd->pw_uid = uid;
    pwd->pw_gid = (gid_t)strtoul(target_gid, NULL, 10);
    *result = pwd;
    return 0;
}
"#,
    )
    .expect("write passwd preload source");
    let output = Command::new("/usr/bin/cc")
        .args(["-shared", "-fPIC", "-O2"])
        .arg(&source)
        .args(["-o"])
        .arg(&library)
        .arg("-ldl")
        .output()
        .expect("compile passwd preload fixture");
    assert!(
        output.status.success(),
        "passwd preload compilation failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    library
}

const GUARD_MISSING_REASON: &str =
    "WORLD_NETFILTER_ENABLE must be set to 1/true/yes before requested network isolation can install nftables rules";

fn detected_manager_manifest() -> &'static str {
    r#"version: 2
managers:
  - name: DetectedManager
    priority: 1
    detect:
      script: "exit 0"
    init:
      shell: |
        export DETECTED_MARKER=1
"#
}

fn write_world_doctor_netfilter_fixture(
    fixture: &DoctorFixture,
    requested: bool,
    enabled: bool,
    world_netfilter_enable_present: bool,
    last_failure_reason: Option<&str>,
    ok: bool,
    status: &str,
) {
    fixture.write_world_doctor_fixture(json!({
        "schema_version": 1,
        "platform": "linux",
        "world_enabled": true,
        "ok": ok,
        "host": {
            "platform": "linux",
            "ok": true,
            "world_fs_mode": "read_only",
            "world_fs_isolation": "workspace",
            "world_fs_require_world": true
        },
        "world": {
            "status": status,
            "schema_version": 2,
            "ok": ok,
            "collected_at_utc": "2026-01-08T00:00:00Z",
            "policy_snapshot_v1_supported": true,
            "policy_resolution_mode": "snapshot_v3",
            "netfilter_status": {
                "requested": requested,
                "enabled": enabled,
                "world_netfilter_enable_present": world_netfilter_enable_present,
                "last_failure_reason": last_failure_reason
            },
            "landlock": {
                "supported": true,
                "abi": 1,
                "reason": null
            },
            "world_fs_strategy": {
                "primary": "overlay",
                "fallback": "fuse",
                "probe": {
                    "id": "enumeration_v1",
                    "probe_file": ".substrate_enum_probe",
                    "result": "pass",
                    "failure_reason": null
                }
            }
        }
    }));
}

fn read_shim_doctor_json(fixture: &DoctorFixture) -> Value {
    let output = fixture
        .command()
        .arg("--world")
        .arg("shim")
        .arg("doctor")
        .arg("--json")
        .output()
        .expect("failed to run shim doctor --json");
    assert!(output.status.success(), "shim doctor --json should succeed");
    serde_json::from_slice(&output.stdout).expect("doctor output JSON")
}

fn write_invalid_workspace_fixture(root: &std::path::Path) {
    let substrate_dir = root.join(".substrate");
    fs::create_dir_all(&substrate_dir).expect("create workspace substrate dir");
    fs::write(
        substrate_dir.join("workspace.yaml"),
        "world:\n  enabled: [true\n",
    )
    .expect("write invalid workspace.yaml");
}

#[test]
fn shim_doctor_human_mode_reports_status_and_path_diagnostics() {
    let manifest = r#"version: 2
managers:
  - name: DetectedManager
    priority: 10
    detect:
      script: "exit 0"
    init:
      shell: |
        export DETECTED_MARKER=1
    repair_hint: |
      export DETECTED_MARKER=1
  - name: MissingManager
    priority: 5
    detect:
      files:
        - "/nonexistent/path"
    init:
      shell: |
        export MISSING_MARKER=1
    repair_hint: |
      export MISSING_MARKER=1
"#;
    let fixture = DoctorFixture::new(manifest);
    fixture.write_hint_event(
        "MissingManager",
        "source ~/.substrate_bashenv so MissingManager loads",
        "2025-11-16T00:00:00Z",
    );

    fixture.write_world_doctor_fixture(json!({
        "platform": "fixture-linux",
        "ok": false,
        "reason": "overlay missing"
    }));
    fixture.write_world_deps_fixture(json!({
        "schema_version": 1,
        "cwd": fixture.home(),
        "inventory_packages": 1,
        "inventory_bundles": 0,
        "inventory_mode": "merged",
        "builtins": "enabled",
        "enabled": ["node"],
        "applied": [
            {
                "kind": "package",
                "name": "node",
                "enabled": true,
                "world": "missing",
                "remediation": "run 'substrate world deps current sync'"
            }
        ]
    }));

    let host_bin = fixture.home().join("host-bin");
    fs::create_dir_all(&host_bin).unwrap();
    let shim_path = fixture.shim_dir().display().to_string();
    let path_value = format!("{}:{}", shim_path, host_bin.display());

    let output = fixture
        .command()
        .env("PATH", &path_value)
        .arg("--world")
        .arg("shim")
        .arg("doctor")
        .output()
        .expect("failed to execute shim doctor");

    assert!(
        output.status.success(),
        "expected shim doctor to succeed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
    assert!(
        stdout.contains("DetectedManager") && stdout.contains("MissingManager"),
        "doctor output should list both managers: {stdout}"
    );
    assert!(
        stdout.contains("Host PATH includes Substrate shims: yes"),
        "doctor output should report host PATH shims state: {stdout}"
    );
    assert!(
        stdout.contains(&shim_path),
        "doctor output should mention shim directory {shim_path}: {stdout}"
    );
    assert!(
        stdout.contains("MissingManager") && stdout.contains("source ~/.substrate_bashenv"),
        "doctor output should surface the latest repair hint: {stdout}"
    );
    assert!(
        stdout.contains("World backend") && stdout.contains("needs attention"),
        "doctor output should summarize world backend status: {stdout}"
    );
    assert!(
        stdout.contains("World deps"),
        "doctor output should include world deps header: {stdout}"
    );
    assert!(
        stdout.contains("Applied: missing/blocked (1): node (missing)"),
        "doctor output should summarize missing/blocked applied deps: {stdout}"
    );
}

#[test]
fn shim_doctor_json_reports_tier2_managers() {
    let manifest = r#"version: 2
managers:
  - name: Bun
    priority: 10
    detect:
      script: "exit 0"
    init:
      shell: |
        export BUN_MARKER=1
    repair_hint: |
      curl https://bun.sh/install | bash
  - name: Volta
    priority: 12
    detect:
      script: "exit 0"
    init:
      shell: |
        export VOLTA_MARKER=1
    repair_hint: |
      export VOLTA_HOME="$HOME/.volta"
"#;
    let fixture = DoctorFixture::new(manifest);
    fixture.write_hint_event(
        "Bun",
        "curl https://bun.sh/install | bash",
        "2025-11-17T00:00:00Z",
    );

    let output = fixture
        .command()
        .arg("--world")
        .arg("shim")
        .arg("doctor")
        .arg("--json")
        .output()
        .expect("failed to run shim doctor --json");
    assert!(
        output.status.success(),
        "shim doctor --json should succeed: stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let report: Value = serde_json::from_slice(&output.stdout).expect("doctor output JSON");
    let states = report["states"]
        .as_array()
        .expect("states array missing from report");
    let bun_state = states
        .iter()
        .find(|state| state["name"] == "Bun")
        .expect("bun state missing");
    assert_eq!(bun_state["repair_available"], true);
    assert_eq!(
        bun_state["last_hint"]["hint"],
        "curl https://bun.sh/install | bash"
    );
    let volta_state = states
        .iter()
        .find(|state| state["name"] == "Volta")
        .expect("volta state missing");
    assert_eq!(volta_state["detected"], true);

    let hints = report["hints"]
        .as_array()
        .expect("hints array missing from report");
    assert!(
        hints.iter().any(|hint| hint["name"] == "Bun"),
        "expected Bun hint in report"
    );
    assert_eq!(report["world"]["platform"], json!(std::env::consts::OS));
    assert_eq!(report["world"]["ok"], json!(true));
    let deps_report = report["world_deps"]["report"].clone();
    assert!(deps_report.is_object(), "world deps report missing");
    assert!(
        deps_report["applied"]
            .as_array()
            .expect("applied array missing")
            .is_empty(),
        "default world deps fixture should report zero applied items"
    );
}

#[test]
fn shim_doctor_snapshot_uses_authenticated_a_under_conflicting_ambient_b() {
    let fixture = DoctorFixture::new(detected_manager_manifest());
    let selected_prefix = fixture.home().join(".substrate");
    fs::write(
        selected_prefix.join("config.yaml"),
        "world:\n  enabled: true\n  deps:\n    builtins: disabled\n    inventory_mode: merged\n    enabled: []\n",
    )
    .expect("write selected Route D config");
    fs::remove_file(fixture.health_dir.join("world_deps.json"))
        .expect("remove selected world deps fixture so Route D collects a snapshot");
    fs::remove_file(fixture.health_dir.join("world_doctor.json"))
        .expect("remove selected world fixture so Route D authenticates the nested child");
    let selected_packages = selected_prefix.join("deps/packages");
    fs::create_dir_all(&selected_packages).expect("create selected inventory");
    for name in [
        "selected-one",
        "selected-two",
        "selected-three",
        "selected-four",
        "selected-five",
    ] {
        fs::write(
            selected_packages.join(format!("{name}.yaml")),
            format!(
                "version: 1\nname: {name}\nrunnable: false\ninstall:\n  method: manual\n  manual_instructions: test only\n"
            ),
        )
        .expect("write selected inventory package");
    }

    let ambient_home = fixture.home().join("ambient-home");
    let ambient_prefix = ambient_home.join(".substrate");
    fs::create_dir_all(ambient_prefix.join("deps/packages"))
        .expect("create conflicting ambient inventory");
    fs::set_permissions(&ambient_home, fs::Permissions::from_mode(0o700))
        .expect("secure conflicting ambient home");
    fs::set_permissions(&ambient_prefix, fs::Permissions::from_mode(0o700))
        .expect("secure conflicting ambient prefix");
    fs::write(
        ambient_prefix.join("config.yaml"),
        "world:\n  enabled: true\n  deps:\n    builtins: disabled\n    inventory_mode: merged\n    enabled: []\n",
    )
    .expect("write conflicting ambient config");
    for name in ["ambient-one", "ambient-two"] {
        fs::write(
            ambient_prefix
                .join("deps/packages")
                .join(format!("{name}.yaml")),
            format!(
                "version: 1\nname: {name}\nrunnable: false\ninstall:\n  method: manual\n  manual_instructions: test only\n"
            ),
        )
        .expect("write conflicting ambient inventory package");
    }
    let ambient_health = ambient_prefix.join("health");
    fs::create_dir(&ambient_health).expect("create conflicting ambient health fixtures");
    fs::write(
        ambient_health.join("world_doctor.json"),
        json!({
            "schema_version": 1,
            "platform": "ambient-b-fixture",
            "ok": true,
            "ambient_fixture_secret": "ambient-b-must-not-appear"
        })
        .to_string(),
    )
    .expect("write conflicting ambient world doctor fixture");
    fs::write(
        ambient_health.join("world_deps.json"),
        json!({
            "schema_version": 1,
            "cwd": ambient_prefix,
            "inventory_packages": 777,
            "inventory_bundles": 0,
            "inventory_mode": "merged",
            "builtins": "disabled",
            "enabled": [],
            "applied": []
        })
        .to_string(),
    )
    .expect("write conflicting ambient world deps fixture");

    let output = fixture
        .command()
        .env("HOME", &ambient_home)
        .env("USERPROFILE", &ambient_home)
        .env("SUBSTRATE_HOME", &ambient_prefix)
        .env("SUBSTRATE_ROOT", &ambient_prefix)
        .env("SHIM_TRACE_LOG", ambient_prefix.join("trace.jsonl"))
        .arg("--world")
        .arg("shim")
        .arg("doctor")
        .arg("--json")
        .output()
        .expect("run typed Route D shim doctor");

    assert!(
        output.status.success(),
        "typed Route D shim doctor should succeed: stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let report: Value = serde_json::from_slice(&output.stdout).expect("Route D doctor JSON");
    assert_eq!(
        report["selected_host_prefix"],
        json!(selected_prefix),
        "typed report must identify selected A"
    );
    assert_eq!(report["world"]["source"], json!("command"));
    assert!(
        report["world"].get("error").is_none(),
        "authenticated nested world doctor must not fail: {report}"
    );
    assert_eq!(
        report["world"]["details"]["host"]["selected_host_prefix"],
        json!(selected_prefix),
        "nested world doctor must receive the authenticated A witness"
    );
    let nested_access = &report["world"]["details"]["host"]["world_socket"]["access"];
    assert!(nested_access.get("current_user").is_none());
    assert!(nested_access.get("current_uid").is_none());
    assert_eq!(report["world_deps"]["source"], json!("command"));
    assert!(
        report["world_deps"]["report"]["inventory_packages"]
            .as_u64()
            .is_some_and(|count| count >= 5),
        "typed Route D snapshot must include selected A's five packages rather than ambient B's two: {report}"
    );
    let rendered = String::from_utf8_lossy(&output.stdout);
    let encoded = InstallBootstrapContextCarrierV1::from_context(
        InstallBootstrapContextV1::new_unix(
            selected_prefix.to_str().expect("UTF-8 selected prefix"),
            "substrate-r2-test",
            unsafe { libc::geteuid() },
        )
        .expect("valid fixture context"),
    )
    .expect("committed fixture context")
    .encode()
    .expect("encoded fixture context");
    assert!(
        !rendered.contains(&ambient_prefix.display().to_string()),
        "Route D diagnostics must not disclose conflicting ambient B: {rendered}"
    );
    assert!(
        !rendered.contains("substrate-r2-test"),
        "Route D diagnostics must not disclose the authenticated principal: {rendered}"
    );
    assert!(
        !rendered.contains(&encoded),
        "Route D JSON must not disclose hidden carrier bytes: {rendered}"
    );
    assert!(!rendered.contains("ambient-b-fixture"));
    assert!(!rendered.contains("ambient-b-must-not-appear"));

    let human_output = fixture
        .command()
        .env("HOME", &ambient_home)
        .env("USERPROFILE", &ambient_home)
        .env("SUBSTRATE_HOME", &ambient_prefix)
        .env("SUBSTRATE_ROOT", &ambient_prefix)
        .env("SHIM_TRACE_LOG", ambient_prefix.join("trace.jsonl"))
        .arg("--world")
        .arg("shim")
        .arg("doctor")
        .output()
        .expect("run typed Route D human diagnostics");
    assert!(human_output.status.success());
    let human_rendered = String::from_utf8_lossy(&human_output.stdout);
    assert!(!human_rendered.contains(&ambient_prefix.display().to_string()));
    assert!(!human_rendered.contains("substrate-r2-test"));
    assert!(!human_rendered.contains(&encoded));
    assert!(!human_rendered.contains("ambient-b-fixture"));
    assert!(!human_rendered.contains("ambient-b-must-not-appear"));

    let trace = fs::read_to_string(&fixture.trace).expect("read Route D trace fixture");
    assert!(!trace.contains(&ambient_prefix.display().to_string()));
    assert!(!trace.contains("substrate-r2-test"));
    assert!(!trace.contains(&encoded));
    assert!(!trace.contains("ambient-b-fixture"));
    assert!(!trace.contains("ambient-b-must-not-appear"));
}

#[test]
fn shim_doctor_rejects_environment_only_malformed_and_tampered_context() {
    let fixture = DoctorFixture::new(detected_manager_manifest());
    let selected_prefix = fixture.home().join(".substrate");
    let uid = unsafe { libc::geteuid() };
    let account_output = Command::new("id")
        .args(["-nu", &uid.to_string()])
        .output()
        .expect("resolve current Unix account");
    assert!(account_output.status.success());
    let account = String::from_utf8(account_output.stdout)
        .expect("UTF-8 Unix account")
        .trim()
        .to_string();
    let context = InstallBootstrapContextV1::new_unix(
        selected_prefix.to_str().expect("UTF-8 selected prefix"),
        &account,
        uid,
    )
    .expect("valid environment-only context");
    let carrier = InstallBootstrapContextCarrierV1::from_context(context)
        .expect("committed environment-only context");
    let encoded = carrier.encode().expect("encoded environment-only context");

    ensure_substrate_built();
    let output = Command::new(binary_path())
        .env("HOME", fixture.home())
        .env("USERPROFILE", fixture.home())
        .env("SUBSTRATE_HOME", &selected_prefix)
        .env("SUBSTRATE_ROOT", &selected_prefix)
        .env(
            "SUBSTRATE_INSTALL_HOST_CONTEXT_COMMITMENT",
            &carrier.host_context_commitment,
        )
        .env("SUBSTRATE_INSTALL_PRIMARY_USER", &account)
        .env("SUBSTRATE_INSTALL_PRIMARY_UID", uid.to_string())
        .env("SUBSTRATE_INSTALL_BOOTSTRAP_CONTEXT_V1", &encoded)
        .current_dir(fixture.home())
        .arg("shim")
        .arg("doctor")
        .arg("--json")
        .output()
        .expect("run environment-only shim doctor invocation");

    assert_eq!(output.status.code(), Some(2));
    assert!(output.stdout.is_empty());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("installed-product invocation witness or --install-prefix is required"));
    assert!(!stderr.contains(&encoded));
    assert!(!stderr.contains(&account));

    let malformed = "route-d-malformed-carrier-must-not-leak";
    let malformed_output = Command::new(binary_path())
        .env("HOME", fixture.home())
        .env("USERPROFILE", fixture.home())
        .env_remove("SUBSTRATE_INSTALL_BOOTSTRAP_CONTEXT_V1")
        .env_remove("SUBSTRATE_INSTALL_HOST_CONTEXT_COMMITMENT")
        .env_remove("SUBSTRATE_INSTALL_PRIMARY_USER")
        .env_remove("SUBSTRATE_INSTALL_PRIMARY_UID")
        .current_dir(fixture.home())
        .arg("--install-bootstrap-context-v1")
        .arg(malformed)
        .arg("shim")
        .arg("doctor")
        .arg("--json")
        .output()
        .expect("run malformed Route D context invocation");
    assert_eq!(malformed_output.status.code(), Some(2));
    assert!(malformed_output.stdout.is_empty());
    let malformed_stderr = String::from_utf8_lossy(&malformed_output.stderr);
    assert!(malformed_stderr.contains("invalid install bootstrap context"));
    assert!(!malformed_stderr.contains(malformed));

    let mut conflicting_commitment = carrier.host_context_commitment.clone();
    let replacement = if conflicting_commitment.starts_with('0') {
        "1"
    } else {
        "0"
    };
    conflicting_commitment.replace_range(..1, replacement);
    let tampered_output = Command::new(binary_path())
        .env("HOME", fixture.home())
        .env("USERPROFILE", fixture.home())
        .env("SUBSTRATE_HOME", &selected_prefix)
        .env("SUBSTRATE_ROOT", &selected_prefix)
        .env(
            "SUBSTRATE_INSTALL_HOST_CONTEXT_COMMITMENT",
            &conflicting_commitment,
        )
        .env("SUBSTRATE_INSTALL_PRIMARY_USER", &account)
        .env("SUBSTRATE_INSTALL_PRIMARY_UID", uid.to_string())
        .env("SUBSTRATE_INSTALL_BOOTSTRAP_CONTEXT_V1", &encoded)
        .current_dir(fixture.home())
        .arg("--install-bootstrap-context-v1")
        .arg(&encoded)
        .arg("shim")
        .arg("doctor")
        .arg("--json")
        .output()
        .expect("run tampered Route D context invocation");
    assert_eq!(tampered_output.status.code(), Some(2));
    assert!(tampered_output.stdout.is_empty());
    let tampered_stderr = String::from_utf8_lossy(&tampered_output.stderr);
    assert!(tampered_stderr.contains("invalid install bootstrap context"));
    assert!(!tampered_stderr.contains(&encoded));
    assert!(!tampered_stderr.contains(&account));
}

#[test]
fn shim_doctor_json_exits_2_before_output_on_invalid_workspace_yaml() {
    let fixture = DoctorFixture::new(detected_manager_manifest());
    let workspace_root = fixture.home().join("workspace");
    fs::create_dir_all(&workspace_root).expect("create workspace root");
    write_invalid_workspace_fixture(&workspace_root);

    let output = fixture
        .command()
        .current_dir(&workspace_root)
        .arg("shim")
        .arg("doctor")
        .arg("--json")
        .output()
        .expect("failed to run shim doctor --json with invalid workspace yaml");

    assert_eq!(
        output.status.code(),
        Some(2),
        "shim doctor should exit 2 for invalid workspace yaml: stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(
        output.stdout.is_empty(),
        "shim doctor should not emit JSON on config error: stdout={}",
        String::from_utf8_lossy(&output.stdout)
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("invalid YAML") || stderr.contains("failed to read"),
        "stderr should report the config parse failure: {stderr}"
    );
}

#[test]
fn shim_doctor_json_mode_surfaces_states_hints_and_path_details() {
    let missing_file = "/nonexistent/path/for/json-test";
    let manifest = format!(
        r#"version: 2
managers:
  - name: JsonDetected
    priority: 1
    detect:
      script: "exit 0"
    init:
      shell: |
        export JSON_DETECTED=1
    repair_hint: |
      export JSON_DETECTED=1
  - name: JsonMissing
    priority: 2
    detect:
      files:
        - "{missing_file}"
    init:
      shell: |
        export JSON_MISSING=1
    repair_hint: |
      export JSON_MISSING=1
"#
    );
    let fixture = DoctorFixture::new(&manifest);
    fixture.write_hint_event(
        "JsonMissing",
        "install JsonMissing locally",
        "2025-11-16T00:00:01Z",
    );
    fixture.write_hint_event(
        "JsonMissing",
        "install JsonMissing locally",
        "2025-11-17T00:00:01Z",
    );

    let host_path = fixture.home().join("bin");
    fs::create_dir_all(&host_path).unwrap();
    let output = fixture
        .command()
        .env("PATH", host_path.display().to_string())
        .arg("--world")
        .arg("shim")
        .arg("doctor")
        .arg("--json")
        .output()
        .expect("failed to execute shim doctor --json");

    assert!(
        output.status.success(),
        "expected shim doctor --json to succeed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let report: Value =
        serde_json::from_slice(&output.stdout).expect("doctor output should be valid JSON");
    let states = report
        .get("states")
        .and_then(Value::as_array)
        .expect("states array missing from report");
    let detected = states
        .iter()
        .find(|value| value.get("name").and_then(Value::as_str) == Some("JsonDetected"))
        .expect("JsonDetected state missing");
    assert_eq!(
        detected.get("detected").and_then(Value::as_bool),
        Some(true)
    );
    assert_eq!(
        detected.get("reason").and_then(Value::as_str),
        Some("script")
    );
    assert!(
        detected
            .get("snippet")
            .and_then(Value::as_str)
            .map(|snippet| snippet.contains("JSON_DETECTED=1"))
            .unwrap_or(false),
        "detected snippet missing from JSON payload: {detected:?}"
    );
    let missing = states
        .iter()
        .find(|value| value.get("name").and_then(Value::as_str) == Some("JsonMissing"))
        .expect("JsonMissing state missing");
    assert_eq!(
        missing.get("detected").and_then(Value::as_bool),
        Some(false)
    );
    assert!(
        missing.get("reason").is_none() || missing.get("reason") == Some(&Value::Null),
        "missing manager should not have a detection reason: {missing:?}"
    );

    let hints = report
        .get("hints")
        .and_then(Value::as_array)
        .expect("hints array missing from report");
    assert_eq!(hints.len(), 1, "doctor should collapse duplicate hints");
    let hint = &hints[0];
    assert_eq!(
        hint.get("name").and_then(Value::as_str),
        Some("JsonMissing")
    );
    assert_eq!(
        hint.get("hint").and_then(Value::as_str),
        Some("install JsonMissing locally")
    );
    assert!(
        hint.get("last_seen")
            .and_then(Value::as_str)
            .map(|ts| ts.contains("2025-11-17"))
            .unwrap_or(false),
        "last_seen timestamp should reflect the newest log entry: {hint:?}"
    );

    let path = report
        .get("path")
        .and_then(Value::as_object)
        .expect("path diagnostics missing from report");
    assert_eq!(
        path.get("host_contains_shims").and_then(Value::as_bool),
        Some(false),
        "json path diagnostics should note that host PATH omits the shim dir"
    );
    let expected_shim_dir = fixture.shim_dir().display().to_string();
    assert_eq!(
        path.get("shim_dir").and_then(Value::as_str),
        Some(expected_shim_dir.as_str()),
        "json path diagnostics should point at the expected shim directory"
    );
    assert!(
        report.get("world").is_some(),
        "world snapshot missing from report"
    );
    assert!(
        report
            .get("world_deps")
            .and_then(|value| value.get("report"))
            .is_some(),
        "world deps section missing from report"
    );
}

#[test]
fn shim_doctor_reports_world_backend_and_deps_errors() {
    let manifest = r#"version: 2
managers:
  - name: SampleManager
    priority: 1
    detect:
      script: "exit 0"
    init:
      shell: |
        export SAMPLE_MANAGER=1
    repair_hint: |
      export SAMPLE_MANAGER=1
"#;
    let fixture = DoctorFixture::new(manifest);
    fixture.write_world_doctor_fixture(json!({
        "platform": "fixture-linux",
        "ok": false,
        "stderr": "failed to connect to /run/substrate.sock"
    }));
    fixture.write_world_deps_fixture(json!({
        "schema_version": 1,
        "cwd": fixture.home(),
        "inventory_packages": 0,
        "inventory_bundles": 0,
        "inventory_mode": "merged",
        "builtins": "enabled",
        "enabled": "invalid",
        "applied": []
    }));

    let json_output = fixture
        .command()
        .arg("--world")
        .arg("shim")
        .arg("doctor")
        .arg("--json")
        .output()
        .expect("failed to run shim doctor --json during error scenario");
    assert!(
        json_output.status.success(),
        "shim doctor --json should succeed even when fixtures contain errors"
    );
    let payload: Value = serde_json::from_slice(&json_output.stdout).expect("doctor output JSON");
    let world = payload
        .get("world")
        .expect("world section missing from doctor JSON");
    assert_eq!(world.get("ok"), Some(&Value::Bool(false)));
    let detail_stderr = world
        .get("details")
        .and_then(Value::as_object)
        .and_then(|details| details.get("stderr"))
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_string();
    assert!(
        detail_stderr.contains("substrate.sock"),
        "expected socket failure details in world snapshot, got: {detail_stderr}"
    );
    let deps = payload
        .get("world_deps")
        .expect("world deps section missing from doctor JSON");
    assert!(
        deps.get("report").is_none(),
        "world deps report should be omitted when fixture parsing fails: {deps:?}"
    );
    let deps_error = deps
        .get("error")
        .and_then(Value::as_str)
        .unwrap_or_default();
    assert!(
        deps_error.contains("invalid world deps fixture"),
        "world deps error should mention invalid fixture: {deps_error}"
    );

    let text_output = fixture
        .command()
        .arg("--world")
        .arg("shim")
        .arg("doctor")
        .output()
        .expect("failed to run shim doctor (text) during error scenario");
    assert!(
        text_output.status.success(),
        "shim doctor text run should succeed even when fixtures fail:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&text_output.stdout),
        String::from_utf8_lossy(&text_output.stderr)
    );
    let stdout = String::from_utf8_lossy(&text_output.stdout);
    assert!(
        stdout.contains("World backend:") && stdout.contains("needs attention"),
        "world backend summary missing during error scenario: {stdout}"
    );
    assert!(
        stdout.contains("World deps:"),
        "doctor output should include world deps header even on error: {stdout}"
    );
    assert!(
        stdout.contains("invalid world deps fixture"),
        "world deps error should be printed in human output: {stdout}"
    );
}

#[test]
fn shim_doctor_repair_appends_snippet_and_creates_backup_files() {
    let manifest = r#"version: 2
managers:
  - name: RepairManager
    priority: 1
    detect:
      script: "exit 0"
    init:
      shell: |
        export REPAIR_MANAGER=1
    repair_hint: |
      # Substrate repair for RepairManager
      export REPAIR_MANAGER=1
      [ -s "$HOME/.repair-manager/init.sh" ] && \\
        . "$HOME/.repair-manager/init.sh"
"#;
    let fixture = DoctorFixture::new(manifest);
    let bashenv_path = fixture.bashenv_path();
    fs::write(&bashenv_path, "export EXISTING_VAR=1\n").expect("failed to seed bashenv");

    let backup_path = fixture.home().join(".substrate_bashenv.bak");
    let run_repair = || {
        fixture
            .command()
            .arg("shim")
            .arg("repair")
            .arg("--manager")
            .arg("RepairManager")
            .arg("--yes")
            .output()
            .expect("failed to run shim repair")
    };

    let first = run_repair();
    assert!(
        first.status.success(),
        "expected shim repair to succeed on first run:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&first.stdout),
        String::from_utf8_lossy(&first.stderr)
    );

    let content = fs::read_to_string(&bashenv_path).expect("failed to read bashenv after repair");
    assert!(
        content.contains("export EXISTING_VAR=1"),
        "existing bashenv lines should be preserved: {content}"
    );
    assert!(
        content.contains("Substrate repair for RepairManager"),
        "repair snippet missing from bashenv: {content}"
    );
    assert!(
        content.matches("REPAIR_MANAGER=1").count() == 1,
        "repair snippet should only be appended once per run: {content}"
    );
    assert!(
        content.contains("SUBSTRATE_BASHENV_ACTIVE"),
        "bashenv guard missing after repair: {content}"
    );

    assert!(
        backup_path.exists(),
        "repair command must create a .substrate_bashenv.bak backup"
    );
    let backup_contents = fs::read_to_string(&backup_path).expect("failed to read bashenv backup");
    assert_eq!(
        backup_contents, "export EXISTING_VAR=1\n",
        "backup should capture the pre-repair bashenv contents"
    );

    let second = run_repair();
    assert!(
        second.status.success(),
        "expected shim repair to remain idempotent:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&second.stdout),
        String::from_utf8_lossy(&second.stderr)
    );
    let second_contents =
        fs::read_to_string(&bashenv_path).expect("failed to read bashenv after second repair");
    assert_eq!(
        content, second_contents,
        "running repair twice should not duplicate the snippet"
    );
}

#[test]
fn shim_doctor_disabled_mode_uses_disabled_statuses_and_omits_probe_fields() {
    let manifest = r#"version: 2
managers:
  - name: SkipWorld
    priority: 1
    detect:
      script: "exit 0"
    init:
      shell: "echo skip"
    repair_hint: "skip"
"#;
    let fixture = DoctorFixture::new(manifest);
    fixture.write_world_doctor_fixture(json!({
        "platform": "fixture-linux",
        "ok": false,
        "stderr": "this fixture should be ignored when diagnostics are disabled"
    }));
    fixture.write_world_deps_fixture(json!({
        "schema_version": 1,
        "cwd": fixture.home(),
        "inventory_packages": 1,
        "inventory_bundles": 0,
        "inventory_mode": "merged",
        "builtins": "enabled",
        "enabled": ["ignored"],
        "applied": [
            {
                "kind": "package",
                "name": "ignored",
                "enabled": true,
                "world": "missing"
            }
        ]
    }));

    let output = fixture
        .command()
        .arg("shim")
        .arg("doctor")
        .arg("--json")
        .output()
        .expect("failed to run shim doctor --json");

    assert!(
        output.status.success(),
        "shim doctor should succeed in disabled mode: stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );

    let report: Value =
        serde_json::from_slice(&output.stdout).expect("doctor output should be valid JSON");
    assert_eq!(report["world"]["status"], json!("disabled"));
    assert_eq!(report["world_deps"]["status"], json!("skipped_disabled"));
    assert_eq!(report["world"]["ok"], json!(false));
    assert_eq!(
        report["world_deps"]["source"].as_str(),
        Some("disabled"),
        "expected world deps source=disabled when diagnostics are disabled"
    );
    for key in ["error", "stderr", "exit_code", "details"] {
        assert!(
            report["world"].get(key).is_none(),
            "expected world.{key} to be omitted in disabled mode: {report:?}"
        );
    }
    for key in ["error", "report"] {
        assert!(
            report["world_deps"].get(key).is_none(),
            "expected world_deps.{key} to be omitted in disabled mode: {report:?}"
        );
    }
}

#[test]
fn shim_doctor_no_world_preserves_cli_flag_disable_attribution() {
    let fixture = DoctorFixture::new(detected_manager_manifest());
    fixture.write_world_doctor_fixture(json!({
        "platform": "fixture-linux",
        "ok": false,
        "stderr": "this fixture should be ignored when diagnostics are disabled"
    }));
    fixture.write_world_deps_fixture(json!({
        "schema_version": 1,
        "cwd": fixture.home(),
        "inventory_packages": 1,
        "inventory_bundles": 0,
        "inventory_mode": "merged",
        "builtins": "enabled",
        "enabled": ["ignored"],
        "applied": [
            {
                "kind": "package",
                "name": "ignored",
                "enabled": true,
                "world": "missing"
            }
        ]
    }));

    let output = fixture
        .command()
        .arg("--no-world")
        .arg("shim")
        .arg("doctor")
        .arg("--json")
        .output()
        .expect("failed to run shim doctor --json with --no-world");
    assert!(
        output.status.success(),
        "shim doctor should succeed in disabled mode"
    );

    let report: Value =
        serde_json::from_slice(&output.stdout).expect("doctor output should be valid JSON");
    assert_eq!(report["world"]["status"], json!("disabled"));
    assert_eq!(
        report["world"]["world_disable_reason"],
        json!("world isolation disabled by CLI flag --no-world")
    );
    assert_eq!(
        report["world"]["world_disable_source"],
        json!({
            "key": "world.enabled",
            "layer": "cli_flag",
            "value_display": false,
            "flag": "--no-world"
        })
    );
    assert!(report["world"]["world_disable_source"].get("env").is_none());
    assert!(report["world"]["world_disable_source"]
        .get("path_display")
        .is_none());
    assert_eq!(report["world_deps"]["status"], json!("skipped_disabled"));
    assert_eq!(
        report["world_deps"]["source"].as_str(),
        Some("disabled"),
        "expected world deps source=disabled when diagnostics are disabled"
    );
    for key in ["error", "stderr", "exit_code", "details"] {
        assert!(
            report["world"].get(key).is_none(),
            "expected world.{key} to be omitted in disabled mode: {report:?}"
        );
    }
    for key in ["error", "report"] {
        assert!(
            report["world_deps"].get(key).is_none(),
            "expected world_deps.{key} to be omitted in disabled mode: {report:?}"
        );
    }
}

#[test]
fn shim_doctor_disabled_mode_prints_exact_contract_lines_without_error_lines() {
    let fixture = DoctorFixture::new(detected_manager_manifest());
    fixture.write_world_doctor_fixture(json!({
        "platform": "fixture-linux",
        "ok": false,
        "stderr": "this fixture should be ignored when diagnostics are disabled"
    }));
    fixture.write_world_deps_fixture(json!({
        "schema_version": 1,
        "cwd": fixture.home(),
        "inventory_packages": 1,
        "inventory_bundles": 0,
        "inventory_mode": "merged",
        "builtins": "enabled",
        "enabled": ["ignored"],
        "applied": [
            {
                "kind": "package",
                "name": "ignored",
                "enabled": true,
                "world": "missing"
            }
        ]
    }));

    let output = fixture
        .command()
        .arg("shim")
        .arg("doctor")
        .output()
        .expect("failed to run shim doctor in disabled mode");
    assert!(
        output.status.success(),
        "shim doctor should succeed in disabled mode"
    );

    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        stdout.contains(
            "World backend:\n  Status: disabled\n  Next: run `substrate world enable` to provision"
        ),
        "disabled world section should match the contract lines: {stdout}"
    );
    assert!(
        stdout.contains("World deps:\n  Status: skipped (world disabled)"),
        "disabled world deps section should match the contract lines: {stdout}"
    );
    assert!(
        !stdout.contains("  Error:"),
        "disabled sections must not print error lines: {stdout}"
    );
}

#[test]
fn shim_doctor_force_world_preserves_enabled_probe_backed_statuses() {
    let fixture = DoctorFixture::new(detected_manager_manifest());
    fixture.write_world_doctor_fixture(json!({
        "platform": "fixture-linux",
        "ok": false,
        "stderr": "failed to connect to /run/substrate.sock"
    }));
    fixture.write_world_deps_fixture(json!({
        "schema_version": 1,
        "cwd": fixture.home(),
        "inventory_packages": 0,
        "inventory_bundles": 0,
        "inventory_mode": "merged",
        "builtins": "enabled",
        "enabled": [],
        "applied": [],
        "applied_error": "world backend unavailable"
    }));

    let output = fixture
        .command()
        .arg("--world")
        .arg("shim")
        .arg("doctor")
        .arg("--json")
        .output()
        .expect("failed to run shim doctor --json with --world");
    assert!(
        output.status.success(),
        "shim doctor --json with --world should succeed"
    );

    let report: Value =
        serde_json::from_slice(&output.stdout).expect("doctor output should be valid JSON");
    assert!(
        report["world"].get("world_disable_reason").is_none(),
        "enabled world doctor snapshots should omit world_disable_reason: {report:?}"
    );
    assert!(
        report["world"].get("world_disable_source").is_none(),
        "enabled world doctor snapshots should omit world_disable_source: {report:?}"
    );
    assert_eq!(report["world"]["status"], json!("needs_attention"));
    assert_eq!(report["world_deps"]["status"], json!("error"));
    assert!(
        report["world"].get("details").is_some(),
        "enabled mode should preserve world details: {report:?}"
    );
    assert!(
        report["world_deps"].get("report").is_some(),
        "enabled mode should preserve world deps reports: {report:?}"
    );
}

#[test]
fn shim_doctor_json_surfaces_world_fs_mode_details() {
    let manifest = r#"version: 2
managers:
  - name: DetectedManager
    priority: 1
    detect:
      script: "exit 0"
    init:
      shell: |
        export DETECTED_MARKER=1
"#;
    let fixture = DoctorFixture::new(manifest);
    fixture.write_world_doctor_fixture(json!({
        "schema_version": 1,
        "platform": "macos",
        "world_enabled": true,
        "ok": true,
        "host": {
            "platform": "macos",
            "ok": true,
            "world_fs_mode": "read_only",
            "world_fs_isolation": "workspace",
            "world_fs_require_world": true,
            "lima": {
                "installed": true,
                "virtualization": true,
                "vm_status": "Running",
                "service_active": true,
                "agent_caps_ok": true,
                "vsock_proxy": true
            }
        },
        "world": {
            "status": "ok",
            "schema_version": 2,
            "ok": true,
            "collected_at_utc": "2026-01-08T00:00:00Z",
            "policy_snapshot_v1_supported": true,
            "policy_resolution_mode": null,
            "netfilter_status": {
                "requested": false,
                "enabled": false,
                "world_netfilter_enable_present": false,
                "last_failure_reason": null
            },
            "landlock": {
                "supported": true,
                "abi": 3,
                "reason": null
            },
            "world_fs_strategy": {
                "primary": "overlay",
                "fallback": "fuse",
                "probe": {
                    "id": "enumeration_v1",
                    "probe_file": ".substrate_enum_probe",
                    "result": "pass",
                    "failure_reason": null
                }
            }
        }
    }));

    let output = fixture
        .command()
        .arg("--world")
        .arg("shim")
        .arg("doctor")
        .arg("--json")
        .output()
        .expect("failed to run shim doctor --json");
    assert!(output.status.success(), "shim doctor --json should succeed");

    let report: Value = serde_json::from_slice(&output.stdout).expect("doctor output JSON");
    assert_eq!(
        report["world"]["details"]["host"]["world_fs_mode"],
        json!("read_only"),
        "shim doctor should surface world_fs_mode from world doctor details"
    );
}

#[test]
fn shim_doctor_json_surfaces_world_socket_and_landlock_details() {
    let manifest = r#"version: 2
managers:
  - name: DetectedManager
    priority: 1
    detect:
      script: "exit 0"
    init:
      shell: |
        export DETECTED_MARKER=1
"#;
    let fixture = DoctorFixture::new(manifest);
    fixture.write_world_doctor_fixture(json!({
        "schema_version": 1,
        "platform": "linux",
        "world_enabled": true,
        "ok": true,
        "host": {
            "platform": "linux",
            "ok": true,
            "world_fs_mode": "read_only",
            "world_fs_isolation": "workspace",
            "world_fs_require_world": true,
            "world_socket": {
                "mode": "socket_activation",
                "socket_path": "/run/substrate.sock",
                "socket_exists": true,
                "probe_ok": true,
                "probe_error": null,
                "systemd_error": null,
                "systemd_socket": null,
                "systemd_service": null
            }
        },
        "world": {
            "status": "ok",
            "schema_version": 2,
            "ok": true,
            "collected_at_utc": "2026-01-08T00:00:00Z",
            "policy_snapshot_v1_supported": true,
            "policy_resolution_mode": null,
            "netfilter_status": {
                "requested": false,
                "enabled": false,
                "world_netfilter_enable_present": false,
                "last_failure_reason": null
            },
            "landlock": {
                "supported": true,
                "abi": 1,
                "reason": null
            },
            "world_fs_strategy": {
                "primary": "overlay",
                "fallback": "fuse",
                "probe": {
                    "id": "enumeration_v1",
                    "probe_file": ".substrate_enum_probe",
                    "result": "pass",
                    "failure_reason": null
                }
            }
        }
    }));

    let output = fixture
        .command()
        .arg("--world")
        .arg("shim")
        .arg("doctor")
        .arg("--json")
        .output()
        .expect("failed to run shim doctor --json");
    assert!(output.status.success(), "shim doctor --json should succeed");

    let report: Value = serde_json::from_slice(&output.stdout).expect("doctor output JSON");
    assert_eq!(
        report["world"]["details"]["host"]["world_socket"]["socket_path"],
        json!("/run/substrate.sock")
    );
    assert_eq!(
        report["world"]["details"]["host"]["world_socket"]["probe_ok"],
        json!(true)
    );
    assert_eq!(
        report["world"]["details"]["world"]["landlock"]["supported"],
        json!(true)
    );
    assert_eq!(
        report["world"]["details"]["world"]["landlock"]["abi"],
        json!(1)
    );
}

#[test]
fn shim_doctor_json_preserves_world_netfilter_default_details() {
    let fixture = DoctorFixture::new(detected_manager_manifest());
    write_world_doctor_netfilter_fixture(&fixture, false, false, false, None, true, "ok");

    let report = read_shim_doctor_json(&fixture);
    assert_eq!(
        report["world"]["details"]["world"]["netfilter_status"],
        json!({
            "requested": false,
            "enabled": false,
            "world_netfilter_enable_present": false,
            "last_failure_reason": null
        })
    );
}

#[test]
fn shim_doctor_json_preserves_world_netfilter_enabled_details() {
    let fixture = DoctorFixture::new(detected_manager_manifest());
    write_world_doctor_netfilter_fixture(&fixture, true, true, true, None, true, "ok");

    let report = read_shim_doctor_json(&fixture);
    assert_eq!(
        report["world"]["details"]["world"]["netfilter_status"],
        json!({
            "requested": true,
            "enabled": true,
            "world_netfilter_enable_present": true,
            "last_failure_reason": null
        })
    );
}

#[test]
fn shim_doctor_json_preserves_world_netfilter_failure_reason_details() {
    let fixture = DoctorFixture::new(detected_manager_manifest());
    write_world_doctor_netfilter_fixture(
        &fixture,
        true,
        false,
        false,
        Some(GUARD_MISSING_REASON),
        false,
        "missing_prereqs",
    );

    let report = read_shim_doctor_json(&fixture);
    assert_eq!(
        report["world"]["details"]["world"]["netfilter_status"],
        json!({
            "requested": true,
            "enabled": false,
            "world_netfilter_enable_present": false,
            "last_failure_reason": GUARD_MISSING_REASON
        })
    );
}
