#![cfg(unix)]

#[path = "common.rs"]
mod common;

use common::{binary_path, ensure_substrate_built, shared_tmpdir};
use serde_json::{json, Value};
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::Command;
use tempfile::{Builder, TempDir};

struct DoctorFixture {
    _temp: TempDir,
    home: PathBuf,
    health_dir: PathBuf,
    passwd_preload: PathBuf,
}

impl DoctorFixture {
    fn new(manifest_contents: &str) -> Self {
        let safe_parent = std::env::var_os("XDG_RUNTIME_DIR")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from(format!("/run/user/{}", unsafe { libc::geteuid() })));
        let temp = Builder::new()
            .prefix("substrate-health-r2-")
            .tempdir_in(safe_parent)
            .expect("allocate secure shim health fixture root");
        let home = temp.path().join("home");
        let prefix = home.join(".substrate");
        fs::create_dir_all(prefix.join("shims")).expect("prepare shim health prefix");
        fs::set_permissions(&home, fs::Permissions::from_mode(0o700))
            .expect("secure fixture account home");
        fs::set_permissions(&prefix, fs::Permissions::from_mode(0o700))
            .expect("secure selected prefix");
        fs::write(prefix.join("trace.jsonl"), "").expect("create trace fixture");
        fs::write(
            prefix.join("manager_init.sh"),
            "# Generated by shim health tests\n",
        )
        .expect("seed manager init fixture");
        fs::write(prefix.join("manager_hooks.yaml"), manifest_contents)
            .expect("project manager manifest into selected prefix");
        let health_dir = prefix.join("health");
        fs::create_dir_all(&health_dir).expect("create health fixture directory");
        let passwd_preload = compile_passwd_preload(temp.path());
        let fixture = Self {
            _temp: temp,
            home,
            health_dir,
            passwd_preload,
        };
        fixture.write_default_world_fixtures();
        fixture
    }

    fn command(&self) -> Command {
        ensure_substrate_built();
        let uid = unsafe { libc::geteuid() };
        let gid = unsafe { libc::getegid() };
        let prefix = self.home.join(".substrate");
        let mut command = Command::new(binary_path());
        command
            .env("TMPDIR", shared_tmpdir())
            .env("HOME", &self.home)
            .env("USERPROFILE", &self.home)
            .env("SUBSTRATE_HOME", &prefix)
            .env("SUBSTRATE_ROOT", &prefix)
            .env("SHIM_TRACE_LOG", prefix.join("trace.jsonl"))
            .env("SUBSTRATE_OVERRIDE_WORLD", "disabled")
            .env("LD_PRELOAD", &self.passwd_preload)
            .env("SUBSTRATE_R2_TEST_UID", uid.to_string())
            .env("SUBSTRATE_R2_TEST_GID", gid.to_string())
            .env("SUBSTRATE_R2_TEST_ACCOUNT", "substrate-r2-test")
            .env("SUBSTRATE_R2_TEST_ACCOUNT_HOME", &self.home)
            .env_remove("SHIM_ORIGINAL_PATH")
            .env_remove("SUBSTRATE_WORLD")
            .env_remove("SUBSTRATE_WORLD_ENABLED")
            .env_remove("SUBSTRATE_WORLD_ID")
            .current_dir(&self.home)
            .arg("--install-prefix")
            .arg(prefix);
        command
    }

    fn write_default_world_fixtures(&self) {
        self.write_world_doctor_fixture(json!({
            "schema_version": 1,
            "platform": std::env::consts::OS,
            "world_enabled": true,
            "ok": true,
            "host": {
                "platform": std::env::consts::OS,
                "ok": true,
                "world_fs_mode": "writable",
                "world_fs_isolation": "workspace",
                "world_fs_require_world": true
            },
            "world": {
                "status": "ok",
                "schema_version": 2,
                "ok": true,
                "collected_at_utc": "2026-01-08T00:00:00Z",
                "policy_snapshot_v1_supported": true,
                "policy_resolution_mode": null,
                "netfilter_status": {
                    "requested": false,
                    "enabled": false,
                    "world_netfilter_enable_present": false,
                    "last_failure_reason": null
                },
                "landlock": { "supported": true, "abi": 3, "reason": null },
                "world_fs_strategy": {
                    "primary": "overlay",
                    "fallback": "fuse",
                    "probe": {
                        "id": "enumeration_v1",
                        "probe_file": ".substrate_enum_probe",
                        "result": "pass",
                        "failure_reason": null
                    }
                }
            }
        }));
        self.write_world_deps_fixture(json!({
            "schema_version": 1,
            "cwd": self.home,
            "inventory_packages": 0,
            "inventory_bundles": 0,
            "inventory_mode": "merged",
            "builtins": "enabled",
            "enabled": [],
            "applied": []
        }));
    }

    fn write_world_doctor_fixture(&self, value: Value) {
        fs::write(self.health_dir.join("world_doctor.json"), value.to_string())
            .expect("write world doctor fixture");
    }

    fn write_world_deps_fixture(&self, value: Value) {
        fs::write(self.health_dir.join("world_deps.json"), value.to_string())
            .expect("write world deps fixture");
    }

    fn home(&self) -> &Path {
        &self.home
    }
}

fn compile_passwd_preload(root: &Path) -> PathBuf {
    let source = root.join("passwd_preload.c");
    let library = root.join("passwd_preload.so");
    fs::write(
        &source,
        r#"#define _GNU_SOURCE
#include <dlfcn.h>
#include <errno.h>
#include <pwd.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
typedef int (*real_getpwuid_r_fn)(uid_t, struct passwd *, char *, size_t, struct passwd **);
int getpwuid_r(uid_t uid, struct passwd *pwd, char *buf, size_t buflen, struct passwd **result) {
    const char *target_uid = getenv("SUBSTRATE_R2_TEST_UID");
    if (target_uid == NULL || uid != (uid_t)strtoul(target_uid, NULL, 10)) {
        static real_getpwuid_r_fn real_fn;
        if (real_fn == NULL) real_fn = (real_getpwuid_r_fn)dlsym(RTLD_NEXT, "getpwuid_r");
        return real_fn(uid, pwd, buf, buflen, result);
    }
    const char *name = getenv("SUBSTRATE_R2_TEST_ACCOUNT");
    const char *home = getenv("SUBSTRATE_R2_TEST_ACCOUNT_HOME");
    const char *target_gid = getenv("SUBSTRATE_R2_TEST_GID");
    const char *passwd = "x", *gecos = "Substrate R2 Test", *shell = "/bin/sh";
    size_t need = strlen(name) + strlen(home) + strlen(passwd) + strlen(gecos) + strlen(shell) + 5;
    if (buflen < need) { *result = NULL; return ERANGE; }
    char *cursor = buf;
#define COPY_FIELD(field, value) do { size_t n = strlen(value) + 1; memcpy(cursor, value, n); pwd->field = cursor; cursor += n; } while (0)
    COPY_FIELD(pw_name, name); COPY_FIELD(pw_passwd, passwd); COPY_FIELD(pw_gecos, gecos);
    COPY_FIELD(pw_dir, home); COPY_FIELD(pw_shell, shell);
    pwd->pw_uid = uid; pwd->pw_gid = (gid_t)strtoul(target_gid, NULL, 10); *result = pwd; return 0;
}
"#,
    )
    .expect("write passwd preload source");
    let output = Command::new("/usr/bin/cc")
        .args(["-shared", "-fPIC", "-O2"])
        .arg(&source)
        .arg("-o")
        .arg(&library)
        .arg("-ldl")
        .output()
        .expect("compile passwd preload fixture");
    assert!(
        output.status.success(),
        "passwd preload compilation failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    library
}

fn write_invalid_workspace_fixture(root: &std::path::Path) {
    let substrate_dir = root.join(".substrate");
    std::fs::create_dir_all(&substrate_dir).expect("create workspace substrate dir");
    std::fs::write(
        substrate_dir.join("workspace.yaml"),
        "world:\n  enabled: [true\n",
    )
    .expect("write invalid workspace.yaml");
}

#[test]
fn health_json_reports_world_deps_missing_and_world_backend_status() {
    let fixture = DoctorFixture::new(
        r#"version: 2
managers:
  - name: HealthyManager
    priority: 10
    detect:
      script: "exit 0"
    init:
      shell: |
        export HEALTHY_MARKER=1
    repair_hint: |
      export HEALTHY_MARKER=1
  - name: MissingManager
    priority: 5
    detect:
      files:
        - "/nonexistent/path"
    init:
      shell: |
        export MISSING_MARKER=1
    repair_hint: |
      export MISSING_MARKER=1
"#,
    );

    fixture.write_world_doctor_fixture(json!({
        "platform": "fixture-linux",
        "ok": false,
        "error": "overlay missing"
    }));

    fixture.write_world_deps_fixture(json!({
        "schema_version": 1,
        "cwd": fixture.home(),
        "inventory_packages": 1,
        "inventory_bundles": 0,
        "inventory_mode": "merged",
        "builtins": "enabled",
        "enabled": ["a"],
        "applied": [
            {"kind": "package", "name": "a", "enabled": true, "world": "missing"}
        ]
    }));

    let output = fixture
        .command()
        .arg("--world")
        .arg("health")
        .arg("--json")
        .output()
        .expect("failed to run substrate health --json");
    assert!(output.status.success(), "health --json should succeed");

    let payload: Value = serde_json::from_slice(&output.stdout).expect("valid JSON payload");
    let summary = payload.get("summary").expect("summary object missing");

    assert!(
        payload.get("world_disable_reason").is_none(),
        "enabled health JSON should omit world_disable_reason: {payload:?}"
    );
    assert!(
        payload.get("world_disable_source").is_none(),
        "enabled health JSON should omit world_disable_source: {payload:?}"
    );
    assert_eq!(summary["missing_managers"], json!(["MissingManager"]));
    assert_eq!(summary["world_ok"], json!(false));
    assert_eq!(summary["world_deps_missing"], json!(["a"]));
    assert_eq!(summary["ok"], json!(false));
}

#[test]
fn health_json_uses_disabled_status_contracts_and_omits_disabled_failures() {
    let fixture = DoctorFixture::new(
        r#"version: 2
managers:
  - name: SampleManager
    priority: 1
    detect:
      script: "exit 0"
    init:
      shell: |
        export SAMPLE_MANAGER=1
    repair_hint: |
      export SAMPLE_MANAGER=1
"#,
    );

    fixture.write_world_doctor_fixture(json!({
        "platform": "fixture-linux",
        "ok": false,
        "stderr": "this fixture should be ignored when diagnostics are disabled"
    }));
    fixture.write_world_deps_fixture(json!({
        "schema_version": 1,
        "cwd": fixture.home(),
        "inventory_packages": 1,
        "inventory_bundles": 0,
        "inventory_mode": "merged",
        "builtins": "enabled",
        "enabled": ["ignored"],
        "applied": [
            {
                "kind": "package",
                "name": "ignored",
                "enabled": true,
                "world": "missing"
            }
        ]
    }));

    let output = fixture
        .command()
        .arg("--no-world")
        .arg("health")
        .arg("--json")
        .output()
        .expect("failed to run substrate health --json with --no-world");
    assert!(
        output.status.success(),
        "health --json should succeed in disabled mode"
    );

    let payload: Value = serde_json::from_slice(&output.stdout).expect("valid JSON payload");
    let summary = payload.get("summary").expect("summary object missing");

    assert_eq!(
        payload["world_disable_reason"],
        json!("world isolation disabled by CLI flag --no-world")
    );
    assert_eq!(
        payload["world_disable_source"],
        json!({
            "key": "world.enabled",
            "layer": "cli_flag",
            "value_display": false,
            "flag": "--no-world"
        })
    );
    assert!(payload["world_disable_source"].get("env").is_none());
    assert!(payload["world_disable_source"]
        .get("path_display")
        .is_none());
    assert_eq!(summary["world_ok"], Value::Null);
    assert!(
        summary.get("world_error").is_none(),
        "disabled mode should omit world_error: {summary:?}"
    );
    assert!(
        summary.get("world_deps_error").is_none(),
        "disabled mode should omit world_deps_error: {summary:?}"
    );
    assert_eq!(summary["world_deps_missing"], json!([]));
    assert_eq!(summary["world_deps_blocked"], json!([]));
    assert_eq!(summary["ok"], json!(true));
    assert!(
        summary.get("failures").is_none(),
        "disabled mode should not emit failure entries: {summary:?}"
    );
}

#[test]
fn health_human_summary_reports_world_deps_unavailable() {
    let fixture = DoctorFixture::new(
        r#"version: 2
managers:
  - name: SampleManager
    priority: 1
    detect:
      script: "exit 0"
    init:
      shell: |
        export SAMPLE_MANAGER=1
    repair_hint: |
      export SAMPLE_MANAGER=1
"#,
    );

    fixture.write_world_deps_fixture(json!({
        "schema_version": 1,
        "cwd": fixture.home(),
        "inventory_packages": 0,
        "inventory_bundles": 0,
        "inventory_mode": "merged",
        "builtins": "enabled",
        "enabled": [],
        "applied": [],
        "applied_error": "world backend unavailable: stubbed"
    }));

    let output = fixture
        .command()
        .arg("--world")
        .arg("health")
        .output()
        .expect("failed to run substrate health");
    assert!(output.status.success(), "health should succeed");

    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        stdout.contains("World deps: unavailable"),
        "expected world deps unavailable summary, got: {stdout}"
    );
    assert!(
        stdout.contains("Overall status: attention required"),
        "expected attention required summary, got: {stdout}"
    );
}

#[test]
fn health_human_summary_uses_disabled_contract_lines_without_guidance() {
    let fixture = DoctorFixture::new(
        r#"version: 2
managers:
  - name: SampleManager
    priority: 1
    detect:
      script: "exit 0"
    init:
      shell: |
        export SAMPLE_MANAGER=1
    repair_hint: |
      export SAMPLE_MANAGER=1
"#,
    );

    fixture.write_world_doctor_fixture(json!({
        "platform": "fixture-linux",
        "ok": false,
        "stderr": "this fixture should be ignored when diagnostics are disabled"
    }));
    fixture.write_world_deps_fixture(json!({
        "schema_version": 1,
        "cwd": fixture.home(),
        "inventory_packages": 1,
        "inventory_bundles": 0,
        "inventory_mode": "merged",
        "builtins": "enabled",
        "enabled": ["ignored"],
        "applied": [
            {
                "kind": "package",
                "name": "ignored",
                "enabled": true,
                "world": "missing"
            }
        ]
    }));

    let output = fixture
        .command()
        .arg("--no-world")
        .arg("health")
        .output()
        .expect("failed to run substrate health in disabled mode");
    assert!(
        output.status.success(),
        "health should succeed in disabled mode"
    );

    let stdout = String::from_utf8_lossy(&output.stdout);
    let reason_index = stdout
        .find("world isolation disabled by CLI flag --no-world")
        .expect("missing disabled attribution line");
    let guidance_index = stdout
        .find("World backend: disabled")
        .expect("missing disabled world guidance");
    assert!(
        reason_index < guidance_index,
        "expected attribution line before disabled guidance: {stdout}"
    );
    assert!(
        stdout
            .contains("World backend: disabled\n  Next: run `substrate world enable` to provision"),
        "expected disabled world contract lines, got: {stdout}"
    );
    assert!(
        stdout.contains("World deps: skipped (world disabled)"),
        "expected disabled world deps contract lines, got: {stdout}"
    );
    assert!(
        !stdout.contains("substrate world deps current"),
        "disabled mode should not print enabled-world guidance: {stdout}"
    );
    assert!(
        stdout.contains("Overall status: healthy"),
        "disabled mode should not report attention required, got: {stdout}"
    );
}

#[test]
fn health_json_is_valid_when_world_deps_fixture_is_invalid() {
    let fixture = DoctorFixture::new(
        r#"version: 2
managers:
  - name: SampleManager
    priority: 1
    detect:
      script: "exit 0"
    init:
      shell: |
        export SAMPLE_MANAGER=1
    repair_hint: |
      export SAMPLE_MANAGER=1
"#,
    );

    fixture.write_world_deps_fixture(json!({
        "schema_version": 1,
        "cwd": fixture.home(),
        "inventory_packages": 0,
        "inventory_bundles": 0,
        "inventory_mode": "merged",
        "builtins": "enabled",
        "enabled": "invalid",
        "applied": []
    }));

    let output = fixture
        .command()
        .arg("--world")
        .arg("health")
        .arg("--json")
        .output()
        .expect("failed to run substrate health --json");
    assert!(output.status.success(), "health --json should succeed");

    let payload: Value = serde_json::from_slice(&output.stdout).expect("valid JSON payload");
    let err = payload["summary"]["world_deps_error"]
        .as_str()
        .unwrap_or_default()
        .to_string();
    assert!(
        err.contains("invalid world deps fixture"),
        "expected world deps fixture error, got: {err}"
    );
}

#[test]
fn health_json_exits_2_before_output_on_invalid_workspace_yaml() {
    let fixture = DoctorFixture::new(
        r#"version: 2
managers:
  - name: SampleManager
    priority: 1
    detect:
      script: "exit 0"
    init:
      shell: |
        export SAMPLE_MANAGER=1
    repair_hint: |
      export SAMPLE_MANAGER=1
"#,
    );

    let workspace_root = fixture.home().join("workspace");
    std::fs::create_dir_all(&workspace_root).expect("create workspace root");
    write_invalid_workspace_fixture(&workspace_root);

    let output = fixture
        .command()
        .current_dir(&workspace_root)
        .arg("health")
        .arg("--json")
        .output()
        .expect("failed to run substrate health --json with invalid workspace yaml");

    assert_eq!(
        output.status.code(),
        Some(2),
        "health should exit 2 for invalid workspace yaml: stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(
        output.stdout.is_empty(),
        "health should not emit JSON on config error: stdout={}",
        String::from_utf8_lossy(&output.stdout)
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("invalid YAML") || stderr.contains("failed to read"),
        "stderr should report the config parse failure: {stderr}"
    );
}
