name: CI feature/*

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - feature/*

jobs:
  build-and-test:
    name: ${{ matrix.os }} / cargo tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-24.04, windows-2022]
    env:
      CARGO_TERM_COLOR: always
      CARGO_WORKSPACE_DIR: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libseccomp-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.89.0
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo check
        run: cargo check --workspace --all-targets

      - name: Cargo clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Cargo build (debug)
        run: cargo build --workspace

      - name: Cargo test
        run: cargo test --workspace --all-targets
